# CKAD Section 3: Application Observability and Maintenance - Examples
# Comprehensive examples for monitoring, logging, and debugging

---
# Pod with Comprehensive Health Checks
apiVersion: v1
kind: Pod
metadata:
  name: healthy-web-app
  labels:
    app: web-app
spec:
  containers:
  - name: web
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 1
      failureThreshold: 3

---
# Pod with Different Probe Types
apiVersion: v1
kind: Pod
metadata:
  name: multi-probe-app
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ['sh', '-c', 'touch /tmp/healthy && sleep 30 && rm -rf /tmp/healthy && sleep 600']
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

---
# TCP Socket Probe Example
apiVersion: v1
kind: Pod
metadata:
  name: tcp-probe-app
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10

---
# Sidecar Logging Pattern
apiVersion: v1
kind: Pod
metadata:
  name: counter-with-sidecar
spec:
  containers:
  - name: count
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "i=0; while true; do echo \"$i: $(date)\" >> /var/log/1.log; echo \"$(date) INFO $i\" >> /var/log/2.log; i=$((i+1)); sleep 1; done"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: count-log-1
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "tail -n+1 -f /var/log/1.log"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: count-log-2
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "tail -n+1 -f /var/log/2.log"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    emptyDir: {}

---
# Application with Metrics Endpoint
apiVersion: v1
kind: Pod
metadata:
  name: metrics-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  labels:
    app: metrics-app
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
      name: http
    - containerPort: 8080
      name: metrics
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

---
# Debug Utilities Pod
apiVersion: v1
kind: Pod
metadata:
  name: debug-utils
spec:
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]

---
# Network Debugging Pod
apiVersion: v1
kind: Pod
metadata:
  name: network-debug
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]

---
# Log Generation Pod for Testing
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
spec:
  containers:
  - name: log-gen
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
    - -c
    - >
      i=0;
      while true;
      do
        echo "$(date) [INFO] Log entry $i";
        echo "$(date) [DEBUG] Debug info $i" >&2;
        i=$((i+1));
        sleep 2;
      done

---
# Multi-Container Pod with Different Log Levels
apiVersion: v1
kind: Pod
metadata:
  name: multi-log-app
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'App: Normal operation'; sleep 5; done"]
  - name: worker
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Worker: Processing job'; sleep 3; done"]
  - name: monitor
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Monitor: System OK'; sleep 10; done"]

---
# Pod with Resource Monitoring
apiVersion: v1
kind: Pod
metadata:
  name: resource-monitor
spec:
  containers:
  - name: app
    image: stress:latest
    command: ["stress"]
    args: ["--cpu", "1", "--timeout", "600s"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

---
# Deployment with Health Checks and Monitoring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitored-app
  labels:
    app: monitored-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitored-app
  template:
    metadata:
      labels:
        app: monitored-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: LOG_LEVEL
          value: "INFO"

---
# Service for Monitored App
apiVersion: v1
kind: Service
metadata:
  name: monitored-app-service
  labels:
    app: monitored-app
spec:
  selector:
    app: monitored-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
# ConfigMap for Logging Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-logging-config
data:
  log-level: "info"
  log-format: "json"
  log-output: "stdout"
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/*.log
        Parser            docker
        Tag               app.*
        Refresh_Interval  5

    [OUTPUT]
        Name  stdout
        Match *

---
# Pod Using Logging ConfigMap
apiVersion: v1
kind: Pod
metadata:
  name: configurable-logging-app
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"$(date) [$LOG_LEVEL] Application message\"; sleep 5; done"]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-logging-config
          key: log-level
    - name: LOG_FORMAT
      valueFrom:
        configMapKeyRef:
          name: app-logging-config
          key: log-format
    volumeMounts:
    - name: config
      mountPath: /etc/fluent-bit
  volumes:
  - name: config
    configMap:
      name: app-logging-config

---
# DaemonSet for Log Collection
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  labels:
    app: log-collector
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
      - name: log-collector
        image: fluent/fluent-bit:1.8
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: app-logging-config

---
# Job for Maintenance Tasks
apiVersion: batch/v1
kind: Job
metadata:
  name: log-cleanup
spec:
  template:
    spec:
      containers:
      - name: cleanup
        image: busybox:1.35
        command: ["/bin/sh"]
        args: ["-c", "find /var/log -name '*.log' -mtime +7 -delete && echo 'Log cleanup completed'"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      restartPolicy: Never
      volumes:
      - name: varlog
        hostPath:
          path: /var/log

---
# CronJob for Regular Health Checks
apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-checker
            image: curlimages/curl:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              curl -f http://monitored-app-service/health || exit 1
              echo "Health check passed at $(date)"
          restartPolicy: OnFailure

---
# Pod with Performance Testing
apiVersion: v1
kind: Pod
metadata:
  name: performance-test
spec:
  containers:
  - name: load-generator
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
    - -c
    - |
      while true; do
        wget -q --spider http://monitored-app-service/
        sleep 0.1
      done
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

---
# Pod for Database Connection Testing
apiVersion: v1
kind: Pod
metadata:
  name: db-connection-test
spec:
  containers:
  - name: db-test
    image: postgres:13
    command: ["/bin/bash"]
    args:
    - -c
    - |
      while true; do
        pg_isready -h postgres-service -p 5432 -U postgres
        sleep 30
      done
    env:
    - name: PGPASSWORD
      value: "password"

---
# Pod with Custom Metrics Exporter
apiVersion: v1
kind: Pod
metadata:
  name: custom-metrics
  labels:
    app: custom-metrics
spec:
  containers:
  - name: metrics-exporter
    image: prom/node-exporter:latest
    ports:
    - containerPort: 9100
      name: metrics
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

---
# Service Monitor for Prometheus (if using Prometheus Operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-metrics
  labels:
    app: app-metrics
spec:
  selector:
    matchLabels:
      app: monitored-app
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# Pod with Init Container for Setup
apiVersion: v1
kind: Pod
metadata:
  name: app-with-setup
spec:
  initContainers:
  - name: setup
    image: busybox:1.35
    command: ['sh', '-c', 'echo "Setup completed at $(date)" > /shared/setup.log']
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /shared
    livenessProbe:
      exec:
        command:
        - cat
        - /shared/setup.log
      initialDelaySeconds: 5
      periodSeconds: 10
  volumes:
  - name: shared-data
    emptyDir: {}

---
# Pod for Log Analysis
apiVersion: v1
kind: Pod
metadata:
  name: log-analyzer
spec:
  containers:
  - name: analyzer
    image: busybox:1.35
    command: ["/bin/sh"]
    args:
    - -c
    - |
      while true; do
        echo "Analyzing logs at $(date)"
        # Simulate log analysis
        grep -i error /var/log/*.log || echo "No errors found"
        sleep 60
      done
    volumeMounts:
    - name: logs
      mountPath: /var/log
  volumes:
  - name: logs
    emptyDir: {}